export const TIPOS_SECCION = [
  {
    id: 'warmup',
    nombre: 'Calentamiento',
    configuracion: {
      usaRondas: false,
      usaTiempoLimite: false,
      usaDescansoEntreEjercicios: true,
      usaDescansoEntreRondas: false,
      usaDescansoEntreSeries: false,
      usaDuracion: true,
      usaPeso: false,
      usaRpe: false,
    },
  },
  {
    id: 'normal',
    nombre: 'Normal',
    configuracion: {
      usaRondas: false,
      usaTiempoLimite: false,
      usaDescansoEntreEjercicios: false,
      usaDescansoEntreRondas: false,
      usaDescansoEntreSeries: true,
      usaDuracion: false,
      usaPeso: true,
      usaRpe: true,
    },
  },
  {
    id: 'circuit',
    nombre: 'Circuito',
    configuracion: {
      usaRondas: true,
      usaTiempoLimite: false,
      usaDescansoEntreEjercicios: true,
      usaDescansoEntreRondas: true,
      usaDescansoEntreSeries: true,
      usaDuracion: false,
      usaPeso: true,
      usaRpe: true,
    },
  },
  {
    id: 'amrap',
    nombre: 'AMRAP',
    configuracion: {
      usaRondas: false,
      usaTiempoLimite: true,
      usaDescansoEntreEjercicios: false,
      usaDescansoEntreRondas: false,
      usaDescansoEntreSeries: true,
      usaDuracion: true,
      usaPeso: true,
      usaRpe: true,
    },
  },
  {
    id: 'technique',
    nombre: 'Técnica',
    configuracion: {
      usaRondas: false,
      usaTiempoLimite: false,
      usaDescansoEntreEjercicios: true,
      usaDescansoEntreRondas: false,
      usaDescansoEntreSeries: true,
      usaDuracion: true,
      usaPeso: true,
      usaRpe: true,
    },
  },
]
